### ISSUE TITLE
Set loading spinner duration to 0 when user prefers reduced motion

### ISSUE THREAD

**Issue by laurakalbag** [small-tech/svelte-nano-donate#1]
I would do this in CSS, but cannot target the Svelte component.

When a person has set their browser or OS to “reduce motion”, we should respect that setting.

I think it’s fine if we make the loading spinner static as a visual cue, and display the alternative text that’s there for assistive technologies to back up the meaning of the image.

To do this in JS, we can use `window.matchMedia("(prefers-reduced-motion: reduce)");` as found in https://since1979.dev/respecting-prefers-reduced-motion-with-javascript-and-react/ to set the `--duration` variable to `0s`.

We should also remove the `.visually-hidden` class on the paragraph inside the `.loading` div, to display the alternative text. (I could do this with CSS, but it’s more semantic to do it with JS.

**Comment by aral** [comment]
We’re now displaying a “Loading exchange rates…” message instead of the spinner when prefers reduced motion is on. Closing.
